package com.preppilot.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Service;

import com.preppilot.dto.FlashcardResponse;

@Service
public class FlashcardParserService {

    public List<FlashcardResponse> parseFlashcards(
            String flashcardText) {

        List<FlashcardResponse> flashcards =
                new ArrayList<>();

        String[] blocks = flashcardText.split(
                "(?i)(?=\\*?\\*?Question\\s*(?:\\d+)?\\s*:\\*?\\*?)"
        );

        for (String block : blocks) {

            if (block.isBlank()) {
                continue;
            }

            String question =
                    extract(
                            block,
                            "Question:",
                            "Answer:"
                    );

            String answer =
                    extract(
                            block,
                            "Answer:",
                            null
                    );

            question = cleanQuestion(question);
            answer = cleanAnswer(answer);

            if (question.isBlank()
                    || answer.isBlank()) {
                continue;
            }

            FlashcardResponse flashcard =
                    new FlashcardResponse();

            flashcard.setQuestion(question);
            flashcard.setAnswer(answer);

            flashcards.add(flashcard);
        }

        if (flashcards.isEmpty()) {
            throw new RuntimeException(
                    "Unable to parse flashcards generated by Gemini");
        }

        return flashcards;
    }

    private String extract(
            String text,
            String start,
            String end) {

        String lowerText =
                text.toLowerCase();

        String lowerStart =
                start.toLowerCase();

        int startIndex =
                lowerText.indexOf(lowerStart);

        if (startIndex == -1) {
            return "";
        }

        startIndex += start.length();

        int endIndex;

        if (end == null) {

            endIndex = text.length();

        } else {

            String lowerEnd =
                    end.toLowerCase();

            endIndex =
                    lowerText.indexOf(
                            lowerEnd,
                            startIndex
                    );

            if (endIndex == -1) {
                endIndex = text.length();
            }
        }

        return text.substring(
                startIndex,
                endIndex
        ).trim();
    }

    private String cleanQuestion(String question) {

        return question
                .replace("*", "")
                .replaceFirst(
                        "(?i)^\\s*\\d+\\s*:\\s*",
                        ""
                )
                .trim();
    }

    private String cleanAnswer(String answer) {

        answer = answer
                .replace("*", "")
                .trim();

        // Remove accidental "Flashcard 2", "Flashcard 3", etc.
        answer = answer.replaceAll(
                "(?i)\\s*\\n\\s*Flashcard\\s+\\d+\\s*$",
                ""
        );

        return answer.trim();
    }
}