package com.preppilot.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Service;

import com.preppilot.dto.QuizQuestionResponse;

@Service
public class QuizParserService {

    public List<QuizQuestionResponse> parseQuiz(String quizText) {

        List<QuizQuestionResponse> questions = new ArrayList<>();

        String[] blocks = quizText.split(
                "(?i)(?=\\*?\\*?Question\\s*(?:\\d+)?\\s*:\\*?\\*?)"
        );

        for (String block : blocks) {

            if (block.isBlank()) {
                continue;
            }

            String questionText =
                    extract(block, "Question", "Option A:");

            String optionA =
                    extract(block, "Option A:", "Option B:");

            String optionB =
                    extract(block, "Option B:", "Option C:");

            String optionC =
                    extract(block, "Option C:", "Option D:");

            String optionD =
                    extract(block, "Option D:", "Correct Answer:");

            String correctAnswer =
                    extract(block, "Correct Answer:", null);

            questionText = cleanQuestion(questionText);
            optionA = cleanText(optionA);
            optionB = cleanText(optionB);
            optionC = cleanText(optionC);
            optionD = cleanText(optionD);
            correctAnswer = cleanCorrectAnswer(correctAnswer);

            // Ignore invalid blocks
            if (questionText.isBlank()
                    || optionA.isBlank()
                    || optionB.isBlank()
                    || optionC.isBlank()
                    || optionD.isBlank()
                    || correctAnswer.isBlank()) {

                continue;
            }

            QuizQuestionResponse question =
                    new QuizQuestionResponse();

            question.setQuestion(questionText);
            question.setOptionA(optionA);
            question.setOptionB(optionB);
            question.setOptionC(optionC);
            question.setOptionD(optionD);
            question.setCorrectAnswer(correctAnswer);

            questions.add(question);
        }

        if (questions.isEmpty()) {
            throw new RuntimeException(
                    "Unable to parse quiz generated by Gemini");
        }

        return questions;
    }

    private String extract(
            String text,
            String start,
            String end) {

        String lowerText = text.toLowerCase();
        String lowerStart = start.toLowerCase();

        int startIndex =
                lowerText.indexOf(lowerStart);

        if (startIndex == -1) {
            return "";
        }

        startIndex += start.length();

        int endIndex;

        if (end == null) {

            endIndex = text.length();

        } else {

            String lowerEnd = end.toLowerCase();

            endIndex =
                    lowerText.indexOf(
                            lowerEnd,
                            startIndex
                    );

            if (endIndex == -1) {
                endIndex = text.length();
            }
        }

        return text.substring(
                startIndex,
                endIndex
        ).trim();
    }

    private String cleanQuestion(String question) {

        return question
                .replace("*", "")
                .replaceFirst(
                        "^\\s*\\d+\\s*:\\s*",
                        ""
                )
                .trim();
    }

    private String cleanText(String text) {

        return text
                .replace("*", "")
                .trim();
    }

    private String cleanCorrectAnswer(String answer) {

        answer = answer
                .replace("*", "")
                .trim();

        if (answer.isBlank()) {
            return "";
        }

        // Extract A/B/C/D from:
        // "Option B"
        // "B"
        // "Correct Answer: Option B"

        if (answer.matches("(?i).*\\bOption\\s+[ABCD]\\b.*")) {

            String letter =
                    answer.replaceAll(
                            "(?i).*\\bOption\\s+([ABCD])\\b.*",
                            "$1"
                    );

            return letter.toUpperCase();
        }

        if (answer.matches("(?i)^[ABCD]$")) {
            return answer.toUpperCase();
        }

        return "";
    }
}